BINDIR = ~nowacki/Applications/bin

all: EC_grid_plot_bin.bash

install: all
	/bin/cp EC_grid_plot_bin.bash $(BINDIR)/EC_grid_plot_bin

.PHONY: clean

clean:
	echo "Nothing to clean for EC_grid_plot_bin"
