BINDIR = ~/Applications/bin

install: GPa2Pa.bash Pa2GPa.bash
	/bin/cp GPa2Pa.bash $(BINDIR)/GPa2Pa
	/bin/cp Pa2GPa.bash $(BINDIR)/Pa2GPa

.PHONY: clean

clean:
	echo "Nothing to clean for GPa2Pa/Pa2GPa"
