#!/bin/bash
# Convert a string of 36 elastic constants into a .ecs file
# Only works for one set of input constants

if [ $# -ne 0 -a $# -ne 2 -a $# -ne 4 ]; then
	echo "Usage: $0 (-necs [necs]) (-r [density])" > /dev/stderr
	echo "   Input is 36 ecs + density in last column if no density supplied" > /dev/stderr
	exit 1
fi

r=-1
necs=36

while [ -n "$1" ]; do
	case "$1" in
		-necs)
			necs=$2
			if [ $necs -ne 21 -a $necs -ne 36 ]; then
				echo "$0: necs must be 21 or 36" > /dev/stderr
				exit 1
			fi
			shift 2
			;;
		-r)
			r=$2
			shift 2
			;;
		*)
			echo "$0: Unrecognised option $1" > /dev/stderr
			exit 2
	esac
done

if [ $necs -eq 36 ]; then
	awk -v r=$r 'NR==1 { 
			for (i=1; i<=6; i++) {
				for (j=i; j<=6; j++) {
					print i,j,$(6*(i-1)+j)
				}
			};
			if (NF == 37 && r == -1) print "7 7",$37 ;
			if (NF == 36 && r != -1) print "7 7",r ;
			if (NF == 36 && r == -1) print "ij2ecs: must supply eith density with -r or in field " NF > "/dev/stderr";
			if (NF == 37 && r != -1) print "ij2ecs: density found both with -r and in field " NF ".  Using last field in preference." > "/dev/stderr"
	}'
else
		awk -v r=$r 'NR==1 { 
			n=1
			for (i=1; i<=6; i++) {
				for (j=i; j<=6; j++) {
					print i,j,$n;
					n = n + 1
				}
			};
			if (NF == 37 && r == -1) print "7 7",$37 ;
			if (NF == 36 && r != -1) print "7 7",r ;
			if (NF == 36 && r == -1) print "ij2ecs: must supply eith density with -r or in field " NF > "/dev/stderr";
			if (NF == 37 && r != -1) print "ij2ecs: density found both with -r and in field " NF ".  Using last field in preference." > "/dev/stderr"
	}'
fi


			
			