BINDIR = ~nowacki/Applications/bin

SCRIPTS = calc-den enter-ecs

all: ${SCRIPTS}

install: ${SCRIPTS}
	/bin/cp ${SCRIPTS} $(BINDIR)/

.PHONY: clean

clean:
	echo "Nothing to clean for calc-den and enter-ecs"

